name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: ly-yuan/blog@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: ly-yuan/blog
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build
        script: "./deploy.sh"
        BUILD_DIR: docs/.vuepress/dist